plugins {
  id 'java'
  id 'application'
}

group = 'com.smartcalc'
version = '1.0.0'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

application {
  mainClass = 'com.smartcalc.server.SmartCalcServer'
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}
